# This Dockerfile embeds a pre-built binary for the given Linux architecture
# Binaries must be built using ./scripts/development/build-binaries.sh first

FROM alpine

# TARGETARCH can be "amd64" or "arm64"
ARG TARGETARCH=""

WORKDIR /app

RUN apk add --no-cache curl su-exec

COPY ./backend/.bin/pocket-id-linux-${TARGETARCH} /app/pocket-id
COPY ./scripts/docker /app/docker

EXPOSE 1411
ENV APP_ENV=production

ENTRYPOINT ["/app/docker/entrypoint.sh"]
CMD ["/app/pocket-id"]
